# Generated by Django 2.2.10 on 2020-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='https://www.time.com', max_length=2200),
            preserve_default=False,
        ),
    ]
