# Generated by Django 3.0.3 on 2020-03-29 16:37

from django.db import migrations, models

from core.utils import random_string_generator
from django.utils.text import Truncator
from django.utils.text import slugify

def gen_slug(apps, schema_editor):
    MyModel = apps.get_model('core', 'Post')
    for row in MyModel.objects.all():
        if not row.slug:
            row.slug = slugify((Truncator(row.title).chars(200) +'-'+ random_string_generator(size=4)))
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200329_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
