# Generated by Django 3.0.3 on 2020-04-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200330_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default='Please enter meta description for better visibility', max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.TextField(max_length=22000),
        ),
    ]
