# Generated by Django 3.0.3 on 2020-06-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200426_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('request', models.IntegerField(default=0)),
                ('aiyath_number', models.IntegerField()),
                ('text', models.CharField(max_length=7000)),
                ('audio_64', models.CharField(max_length=100)),
                ('audio_128', models.CharField(max_length=100)),
                ('surah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=200)),
                ('surah_englishName', models.CharField(max_length=100)),
                ('surah_englishNameTranslation', models.CharField(max_length=500)),
                ('surah_numberOfAyahs', models.IntegerField()),
                ('surah_revelationType', models.CharField(max_length=100)),
                ('numberInSurah', models.IntegerField()),
                ('juz', models.IntegerField()),
                ('manzil', models.IntegerField()),
                ('page', models.IntegerField()),
                ('ruku', models.IntegerField()),
                ('hizbQuarter', models.IntegerField()),
                ('sajda', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
