# Generated by Django 3.0.3 on 2020-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quran'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran',
            name='slug',
            field=models.CharField(default='1:1', max_length=10),
        ),
    ]
