# Generated by Django 3.0.3 on 2020-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quran_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='slug',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
