# Generated by Django 3.0.3 on 2020-05-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accountcode',
            name='user_connected',
        ),
        migrations.AddField(
            model_name='accountcode',
            name='chat_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='MjkosndWhS', max_length=10, unique=True),
        ),
    ]
