# Generated by Django 3.0.3 on 2020-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200531_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='gvleSECFQw', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
