# Generated by Django 3.0.3 on 2020-06-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200607_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='yjEqVdkWTW', max_length=10, unique=True),
        ),
    ]
